trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroupName: 'myResourceGroup'
  functionAppName: 'myPrivateFunctionApp'

steps:
- task: AzureCLI@2
  displayName: "Whitelist Azure DevOps Agent IPs"
  inputs:
    azureSubscription: 'your-service-connection-name'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # Get the list of Azure DevOps IP ranges
      ADO_IPS=$(curl -s https://learn.microsoft.com/en-us/azure/devops/_static/whitelist.txt)

      # Convert IP ranges to JSON array format (assuming App Service IP restrictions)
      IP_RULES=$(echo "$ADO_IPS" | awk '{print "{\"ipAddress\":\""$1"\",\"action\":\"Allow\",\"priority\":100," \
              "\"name\":\"ADO-Agent-"NR"\"},"}')

      # Remove trailing comma and wrap in brackets to form JSON array
      IP_RULES_JSON="[${IP_RULES%,}]"

      # Apply the IP restrictions to the Function App
      az functionapp config access-restriction set \
        --resource-group $resourceGroupName \
        --name $functionAppName \
        --rules "$IP_RULES_JSON"
    failOnStandardError: true
